AND pc.title NOT LIKE "%barcod%"
AND pc.title NOT LIKE "%biogeo%"
AND pc.title NOT LIKE "%colonization%"
AND pc.title NOT LIKE "%communit%"
AND pc.title NOT LIKE "%comparative gen%"
AND pc.title NOT LIKE "%conservation gen%"
AND pc.title NOT LIKE "%conspecificity%"
AND pc.title NOT LIKE "%classification%"
AND pc.title NOT LIKE "%cryptic%"
AND pc.title NOT LIKE "differentiation of strains"
AND pc.title NOT LIKE "%discrimination%"
AND pc.title NOT LIKE "%dispersal%"
AND pc.title NOT LIKE "%distribution%"
AND pc.title NOT LIKE "%ecotype%"
AND pc.title NOT LIKE "%endemi%"
AND pc.title NOT LIKE "ETS"
AND pc.title NOT LIKE "%first re%"
AND pc.title NOT LIKE "gen. nov."
AND pc.title NOT LIKE "genetic characterization"
AND pc.title NOT LIKE "genetic distinctions"
AND pc.title NOT LIKE "genetic heterogeneity"
AND pc.title NOT LIKE "genetic identifiaction"
AND pc.title NOT LIKE "genetic lineage"
AND pc.title NOT LIKE "%genetic vari%"
AND pc.title NOT LIKE "genomic evidence"
AND pc.title NOT LIKE "%genetic vari%"
AND pc.title NOT LIKE "%genotyp%"
AND pc.title NOT LIKE "%genus%"
AND pc.title NOT LIKE "%geographic%"
AND pc.title NOT LIKE "%hybrid%"
AND pc.title NOT LIKE "%intergenic region%"
AND pc.title NOT LIKE "%interspeci%"
AND pc.title NOT LIKE "%intra-specific%"
AND pc.title NOT LIKE "%intraspecific%"
AND pc.title NOT LIKE "%invasi%"
AND pc.title NOT LIKE "%isolat%"
AND pc.title NOT LIKE "ITS%"
AND pc.title NOT LIKE "%marker%"
AND pc.title NOT LIKE "%molecular %"
AND pc.title NOT LIKE "%morpholog%"
AND pc.title NOT LIKE "%occurrence%"
AND pc.title NOT LIKE "%phyletic%"
AND pc.title NOT LIKE "%phylo%"
AND pc.title NOT LIKE "%phyly%"
AND pc.title NOT LIKE "%ploid%"
AND pc.title NOT LIKE "%population%"
AND pc.title NOT LIKE "%prevalence%"
AND pc.title NOT LIKE "%radiation%"
AND pc.title NOT LIKE "rapid identification"
AND pc.title NOT LIKE "rDNA"
AND pc.title NOT LIKE "repeat"
AND pc.title NOT LIKE "ribosomal"
AND pc.title NOT LIKE "sens."
AND pc.title NOT LIKE "sensu"
AND pc.title NOT LIKE "sp."
AND pc.title NOT LIKE "spacer"
AND pc.title NOT LIKE "%species%"
AND pc.title NOT LIKE "%synonym%"
AND pc.title NOT LIKE "%systematic%"